// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xwazwxdwhgqtlopcutqt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh3YXp3eGR3aGdxdGxvcGN1dHF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMjYyNDgsImV4cCI6MjA3MTgwMjI0OH0.N03JShHOStITZuXIBVMa_aAtH1mv5ObpAzYJ_inUBC8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});